---

- hosts: cka1.hallo.io
  remote_user: root
  gather_facts: no
  tasks:
  
  - name: Letting iptables see bridged traffic
    lineinfile:
      path: /etc/sysctl.d/k8s.conf
      line: "{{item}}"
      create: yes
    loop:
      - "net.bridge.bridge-nf-call-ip6tables = 1"
      - "net.bridge.bridge-nf-call-iptables = 1"
