---

- hosts: all
  remote_user: root
  gather_facts: no
  tasks:
  
  - name: Changing sshd_config UseDNS
    lineinfile:
      path: /etc/ssh/sshd_config
      line: 'UseDNS no'
      regex: '#^UseDNS'
      state: present
    notify:
      - restart sshd
    tags:
      - usedns
      
    
  
  - name: Letting iptables see bridged traffic
    lineinfile:
      path: /etc/sysctl.d/k8s.conf
      line: "{{item}}"
      create: yes
    loop:
      - "net.bridge.bridge-nf-call-ip6tables = 1"
      - "net.bridge.bridge-nf-call-iptables = 1"

  - name: Check required ports for masters

    firewalld:
      port: "{{item}}"
      permanent: yes
      state: enabled
    notify:
      - name: reload firewalld

    loop:
      - 6443/tcp
      - 2379-2380/tcp
      - 10250-10252/tcp

  - name: Check required ports for workers
    fireawlld:
      port: "{{item}}"
      permanent: yes
      state: enabled
    loop:
      - 30000-32767/tcp
    notify:
      - reload firewalld
    
  handlers:
    - name: restart sshd
      systemd:
        name: sshd
        state: restarted
    - name: reload firewalld
      command: firewall-cmd --reload
     
