---

- hosts: all
  remote_user: root
  gather_facts: no
  tasks:

  
  - name: Changing sshd_config UseDNS
    lineinfile:
      path: /etc/ssh/sshd_config
      line: 'UseDNS no'
      regex: '#^UseDNS'
      state: present
    notify:
      - restart sshd
    tags:
      - usedns

  - name: update systems
    yum:
      name: '*'
      state: latest
  
  - name: Letting iptables see bridged traffic
    lineinfile:
      path: /etc/sysctl.d/k8s.conf
      line: "{{item}}"
      create: yes
    loop:
      - "net.bridge.bridge-nf-call-ip6tables = 1"
      - "net.bridge.bridge-nf-call-iptables = 1"
      
  - name: Install docker repository
    yum_repository:
      name: Docker CE Stable - $basearch
      file: docker-ce
      baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
      enabled: 1
      gpgcheck: 1
      gpgkey: https://download.docker.com/linux/centos/gpg

 
    
  handlers:
    - name: restart sshd
      systemd:
        name: sshd
        state: restarted
     
